version: '3.9'

#services:
#  db:
#    image: postgres:14.1-alpine
#    volumes:
#      - ./data/db:/var/lib/postgresql/data
#  postgres:
#    build: .
#    ports:
#      - "6543:5432"
#    environment:
#      - POSTGRES_NAME=postgres
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=postgres
#    depends_on:
#      - db
services:
  app:
    image: postgres:14.1-alpine
    ports:
      - 8001:5432
    volumes:
      - ./14/data/db:/var/lib/postgresql/data
    environment:
      POSTGRES_NAME: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: todos
